### PR TITLE
switch to Gurobi Sphinx theme

### PR DESCRIPTION
**Pull request by mattmilten**

### CODE REVIEW

**Comment by pobonomo** [comment]
@mattmilten I made a few tweaks.

There are two things that annoy me in particular with the current theme:
- The Gurobi Optimization logo linking to the top page of the documentation of Gurobi ML. I think that it is confusing. I would expect a Gurobi logo to link to gurobi.com. I also don't like that there is no link to gurobi.com in every page of the documentation.
- I think that the name of the package or title of the documentation should appear in every page.

I could tweak the sidebar to fix these two now (normally you can see the result there https://gurobi-machinelearning.readthedocs.io/en/use-gurobi-theme/).
Overall, I am not sure it is really more ergonomic than the current theme but fine.

Maybe you should consider the tweaks for the theme itself.

**Comment by mattmilten** [comment]
> There are two things that annoy me in particular with the current theme:
> 
> * The Gurobi Optimization logo linking to the top page of the documentation of Gurobi ML. I think that it is confusing. I would expect a Gurobi logo to link to gurobi.com. I also don't like that there is no link to gurobi.com in every page of the documentation.
> * I think that the name of the package or title of the documentation should appear in every page.
> 
> I could tweak the sidebar to fix these two now (normally you can see the result there https://gurobi-machinelearning.readthedocs.io/en/use-gurobi-theme/). Overall, I am not sure it is really more ergonomic than the current theme but fine.
> 
> Maybe you should consider the tweaks for the theme itself.

Yes, these things really are not ideal and should be fixed in the theme instead.

**Comment by pobonomo** [comment]
OK thanks for create the items.

In spite of these two small things I am starting to like it. So I'll merge this.

**Review by pobonomo — COMMENTED** [review]
Good

**Pull request merged**
