### PR TITLE
Create separate tox targets

### PR DESCRIPTION
**Pull request by twbraam**
So we can test the ML packages separately, without having eachother potentially polluting the environment

### CODE REVIEW

**Comment by twbraam** [comment]
We now have separate envs in tox for each of the ml package dependencies. I think this makes the tests better since there is no cross-pollution and we can be more sure that there are no hidden dependencies of one ML package on the other.

I put the `requirements.txt` files into separate folders. Not sure if this is the best location. We can just as well put it in root, but that might overcrowd it.

**Comment by pobonomo** [comment]
I think that the remaining issue (at least one of them) is my fault. I was using keras to import a dataset in the pytorch example.

I know how to fix it hopefully.

**Comment by pobonomo** [comment]
I fixed two issues and now it works on my machine but this PR seems to be unhappy with GH actions

**Comment by pobonomo** [comment]
Seems to work now

**Comment by twbraam** [comment]
Luckily there's no big impact on runtime with all these multiple envs.

**Comment by twbraam** [comment]
I think we can even remove the `rm` part now. I fixed something that possibly required that action. Let me test this tomorrow

**Comment by twbraam** [comment]
FYI when you declare something in the `[testenv]` block, this will be inherited by all the `[testenv:*]` blocks if they are not overwritten there. So no need to declare everything everywhere.

**Review by pobonomo — APPROVED** [review]
Looks fine to me to merge

**Pull request merged**
